# base
FROM node:alpine AS base

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .



FROM base as builder

WORKDIR /usr/src/app

RUN npm run build


# for production

FROM node:alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./

EXPOSE 3000

ENTRYPOINT ["node","./app.js"]